name: assessment
description: "Wordup assessment"
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # infrastructures  ->
  go_router: ^14.8.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1

  # <- infrastructure

  # presentation ->
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.0
  shimmer: ^3.0.0
  video_player: ^2.9.3
  just_audio: ^0.9.46
  flutter_tts: ^4.2.2
  # <- presentation

  # network ->
  dio: ^5.8.0+1
  archive: ^4.0.4
  # <- network

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: 2.7.0
  build_runner: ^2.4.15

  flutter_lints: ^5.0.0
  freezed: ^3.0.3
  json_serializable: ^6.9.0
flutter:
  
  
  uses-material-design: true

  assets:
    - .env


